//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void setup(); \
	void connectWifi(); \
	void loop(); \
	void onStationModeConnected(const WiFiEventStationModeConnected& evt); \

